# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19UyviKtgeo61AYCtiPLsHW2TVyyc0gLJ
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/kimbab.csv')

mean_sajang = np.mean(data['사장님'])
mean_chulsu = np.mean(data['철수'])
var_sajang = np.var(data['사장님'])
var_chulsu = np.var(data['철수'])
std_sajang = np.std(data['사장님'])
std_chulsu = np.std(data['철수'])

print("사장님----------")
print(f"평균: {mean_sajang}")
print(f"분산: {var_sajang}")
print(f"표준편차: {std_sajang}")

print("\n철수----------")
print(f"평균: {mean_chulsu}")
print(f"분산: {var_chulsu}")
print(f"표준편차: {std_chulsu}")


plt.hist(data['사장님'], bins=20, alpha=0.5, label='사장님')
plt.hist(data['철수'], bins=20, alpha=0.5, label='철수')
plt.title('김밥')
plt.legend()
plt.show()