# -*- coding: utf-8 -*-
"""1416한예준.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18XFv76u6dKcehjPkWKCFfw2nrtnil4Bi
"""

scoreDict = {
    "국어" : 90,
    "영어": 70,
    "수학":90,
    "파이썬":80,
    "알고리즘":100
}

print(scoreDict["국어"])

print(scoreDict.get("미술", "과목없음"))

"""해결문제) 5개의 숫자를 입력받아서 리스트에 저장하고 짝수와 홀수 리스트를 만드시오"""

list = []
evenList = []
oddList = []

for i in range(5) :
  list.append(int(input()))

for i in range(5) :
  if (list[i] % 2 == 0) :
    evenList.append(list[i])
  else :
    oddList.append(list[i])

print(evenList)
print(oddList)

y = [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
yavg = [14.9, 14.6, 14.5, 15.3, 15.1, 15.4, 15.7, 15.2, 15.1, 15.7]
ymax = [34.1, 33, 34.5, 35, 32.9, 33.5, 37.3, 36.2, 36.4, 35]
ymin = [19, 18.8, 18.6, 19.5, 19.2, 19.5, 19.8, 19.6, 19.2, 19.8]

# + 홀수년도만 출력
# + 년도 출력하기
# + 년도와 평균기온 딕셔너리 만들기
# + 평균기온 최소일 때 해당년도 추출하기 예) 2012년 – 14.5℃
# + 최고기온 최대일 때 해당년도 추출하기 예) 2016년 – 19.6℃ 
# + 최저기온 최소일 때 해당년도 추출하기 예) 2012년 – 18.6℃

# https://github.com/lsa-src/winterSch/blob/main/weatherStatistics.py

yOdd = []

for item in y :
  if item % 2 == 1 :
    yOdd.append(item)

print(f"홀수년도 : {yOdd}")

y = [str(item) for item in y]
print(y)

ytemp = dict(zip(y, yavg))
ytemp

mint = min(ytemp.values())
mint

ytemp.values()

for y, tp in ytemp.items() :
  if tp == mint :
    print(y)

for y, tp in ytemp.items() :
  if tp == max(ytemp.values()) :
    print(y)
    break;