# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KU3LFvFBzc9OjQanfjuLoYhlkamzDd0R
"""

import numpy as np
import matplotlib.pyplot as plt

number_of_simulation = 1000
number_of_iteration = 20
all_means = []


def simulate_dice(number_of_simulation):
    results = np.random.randint(1, 7, number_of_simulation)
    mean_result = np.mean(results)
    return mean_result


for run in range(1, number_of_iteration + 1):
    mean_result = simulate_dice(number_of_simulation * run)
    print(f" {number_of_simulation * run}: {mean_result:.4f}")
    all_means.append(mean_result)

plt.figure(figsize=(10, 6))
plt.scatter(range(number_of_iteration), all_means, color='blue')
plt.axhline(y=3.5, color='red')
plt.xlabel('실행횟수')
plt.ylabel('기댓값')
plt.legend()
plt.show()
