# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tyGTq8lVj9rWQf0o-Nw7RaAzOtHfwAzp
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

f = open('/body.txt')
height = []
weight = []
for line in f.readlines():
    items = line.split()
    height.append(float(items[0]))
    weight.append(float(items[1]))
npheight= np.array(height)
npweight= np.array(weight)

f.close()

data = {'Height': height, 'Weight': weight}
df = pd.DataFrame(data)

r = df.corr()

plt.figure(figsize=(8, 6))
sns.heatmap(r, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('히트맵')
plt.show()

print(correlation)

import numpy as np
import matplotlib.pyplot as plt

f = open('/body.txt')
height = []
weight = []

for line in f.readlines():
    items = line.split()
    height.append(float(items[0]))
    weight.append(float(items[1]))

npheight = np.array(height)
npweight = np.array(weight)

f.close()

r = np.corrcoef(npheight, npweight)[0, 1]

plt.plot(height, weight, 'bo', 'r--')
plt.text(5, 170, ' r = '+str(r))

plt.show()